### ISSUE TITLE
Newlines overwrite link text when inserting a link

### ISSUE THREAD

**Issue by dnsl48** [springload/wagtaildraftail#20] opened 2017-03-10 03:09 UTC
How to reproduce:

1. write a sentence
2. press `Shift+Alt+Left`
3. press `Link` button
4. choose a link
5. see that the text is not highlighted anymore
6. press `Enter`
7. `newline` symbol overwrote the link sentence

**Comment by thibaudcolas** [comment] 2017-11-16 16:10
Moving this to https://github.com/springload/draftail/issues/108 as the issue is not specific to the editor being within Wagtail.

**Closed as completed by thibaudcolas** 2017-11-16 16:10 UTC
Labels: bug
