### ISSUE TITLE
Link editing and removal are unreliable

### ISSUE THREAD

**Issue by tomdyson** [springload/wagtaildraftail#47] opened 2017-05-17 08:26 UTC
See screencast. I haven't been able to establish a pattern!

![draftail-link-edit](https://cloud.githubusercontent.com/assets/15543/26144967/a33f0828-3ae2-11e7-8ee9-2fc48a54c2de.gif)

**Comment by thibaudcolas** [comment] 2017-05-17 09:20
I think I have experienced this too, didn't manage to pinpoint the cause either. Will investigate.

**Comment by jjanssen** [comment] 2017-05-19 08:54
It seems like the initial cause itself is a part of the prefixing icon and not being able to select the first letter when visible (the w in Toms screen). At that point the cursor will jump to the beginning of the icon which does not hold the link but still shows the dialog.

When you disable the icon this is partially the same behaviour except the 1st letter is now clickable / targetable. But also when the cursor is in front of the first letter, it shows the dialog, but does not respond to either Edit or Remove.

**Update:** DraftJS Link demo shows the same behaviour with cursor in front of the text.

**Comment by loicteixeira** [comment] 2017-05-22 05:17
Regardless of what default is chosen, the configuration should be documented (or linked to the draft one?)

**Comment by thibaudcolas** [comment] 2017-11-16 16:15
Moving this to https://github.com/springload/draftail/issues/109, as the issue isn't specific to WagtailDraftail.

**Closed as completed by thibaudcolas** 2017-11-16 16:15 UTC
Labels: bug
